version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - settings.env
    volumes:
      - ../cert/nginx:/etc/nginx/conf.d
      - ../cert/www:/var/www/certbot
      - ../cert/conf:/etc/letsencrypt
